#!/usr/bin/env perl
# Reads UMR file generated by Federica's converter from UD. Re-computes all
# Index lines based on corresponding Words lines so that left margin of each
# index aligns with the left margin of the corresponding word, and no indices
# are glued together.
# Copyright © 2025 Dan Zeman <zeman@ufal.mff.cuni.cz>
# License: GNU GPL

use utf8;
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');

my %sinfo;
while(<>)
{
    # If this is a sentence/token information line, save it for later.
    if(m/^(Index|Words|Word Gloss \([a-z]+\)|Morphemes|Morpheme Gloss \([a-z]+\)|Morpheme Category|Sentence|Sentence Gloss \([a-z]+\)):\s*(.+)/)
    {
        my $header = $1;
        my $contents = $2;
        $contents =~ s/\s*\r?\n$//;
        if(exists($sinfo{$header}))
        {
            die("Repeated header '$header'");
        }
        $sinfo{$header} = $contents;
    }
    else
    {
        # On the first line after sentence/token information lines, process them and print them.
        if(scalar(keys(%sinfo)))
        {
            #print STDERR ("Found the following headers: ", join(', ', sort(keys(%sinfo))), "\n");
            #print STDERR ("Current line: $_");
            my $indexline = $sinfo{Index};
            my $wordline = $sinfo{Words};
            die("Missing Index line") if(!defined($indexline));
            die("Missing Words line") if(!defined($wordline));
            my @words = split(/\s+/, $wordline);
            my @indices;
            for(my $i = 0; $i <= $#words; $i++)
            {
                my $index = $i+1;
                push(@indices, $index);
            }
            unshift(@indices, 'Index:');
            unshift(@words, 'Words:');
            my @table = (\@indices, \@words);
            if(exists($sinfo{'Word Gloss (en)'}))
            {
                my @englosses = split(/\s+/, $sinfo{'Word Gloss (en)'});
                unshift(@englosses, 'Word Gloss (en):');
                push(@table, \@englosses);
            }
            if(exists($sinfo{'Word Gloss (es)'}))
            {
                my @esglosses = split(/\s+/, $sinfo{'Word Gloss (es)'});
                unshift(@esglosses, 'Word Gloss (es):');
                push(@table, \@esglosses);
            }
            my @formatted = format_table(@table);
            foreach my $row (@formatted)
            {
                my $line = join(' ', @{$row});
                $line =~ s/\s+$//;
                print("$line\n");
            }
            # Now print the other sinfo lines that we did not modify.
            foreach my $header ('Morphemes', 'Morpheme Gloss (en)', 'Morpheme Gloss (es)', 'Morpheme Category', 'Sentence', 'Sentence Gloss (en)', 'Sentence Gloss (es)')
            {
                if(defined($sinfo{$header}))
                {
                    print("$header: $sinfo{$header}\n");
                }
            }
            %sinfo = ();
        }
        # Pass all other lines simply through.
        print;
    }
}



#------------------------------------------------------------------------------
# Formats a table using spaces, assuming a fixed-width font. Strings align to
# the left (they are padded by spaces from the right).
#------------------------------------------------------------------------------
sub format_table
{
    my @srctable = @_; # array of array references
    # Determine the required width of each column.
    my @widths;
    foreach my $row (@srctable)
    {
        for(my $i = 0; $i <= $#{$row}; $i++)
        {
            my $cell = $row->[$i];
            my $l = vlength($cell);
            if(!defined($widths[$i]) || $l > $widths[$i])
            {
                $widths[$i] = $l;
            }
        }
    }
    # Create a new table with cells padded with spaces as needed.
    my @tgttable = ();
    foreach my $row (@srctable)
    {
        my @tgtrow = ();
        for(my $i = 0; $i <= $#widths; $i++)
        {
            my $cell = $row->[$i] // '';
            my $pad = ' ' x ($widths[$i]-vlength($cell));
            $tgtrow[$i] = $cell.$pad;
        }
        push(@tgttable, \@tgtrow);
    }
    return @tgttable;
}



#------------------------------------------------------------------------------
# Estimates visible length of a string. Ignores combining diacritics because
# they should use the position of the previous character.
#------------------------------------------------------------------------------
sub vlength
{
    my $x = shift;
    # Remove modifier characters.
    $x =~ s/\pM//g;
    return length($x);
}
