#!/usr/bin/env perl
# Reads UMR file generated by Federica's converter from UD. Re-computes all
# Index lines based on corresponding Words lines so that left margin of each
# index aligns with the left margin of the corresponding word, and no indices
# are glued together.
# Copyright © 2025 Dan Zeman <zeman@ufal.mff.cuni.cz>
# License: GNU GPL

use utf8;
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');

my %sinfo;
while(<>)
{
    # If this is a sentence/token information line, save it for later.
    if(m/^(Index|Words|Word Gloss \([a-z]+\)|Morphemes|Morpheme Gloss \([a-z]+\)|Morpheme Category|Sentence|Sentence Gloss \([a-z]+\)):\s*(.+)/)
    {
        my $header = $1;
        my $contents = $2;
        $contents =~ s/\s*\r?\n$//;
        if(exists($sinfo{$header}))
        {
            die("Repeated header '$header'");
        }
        $sinfo{$header} = $contents;
    }
    else
    {
        # On the first line after sentence/token information lines, process them and print them.
        if(scalar(keys(%sinfo)))
        {
            #print STDERR ("Found the following headers: ", join(', ', sort(keys(%sinfo))), "\n");
            #print STDERR ("Current line: $_");
            my $indexline = $sinfo{Index};
            my $wordline = $sinfo{Words};
            die("Missing Index line") if(!defined($indexline));
            die("Missing Words line") if(!defined($wordline));
            my @words = split(/\s+/, $wordline);
            my @indices;
            for(my $i = 0; $i <= $#words; $i++)
            {
                my $index = $i+1;
                my $lw = length($words[$i]);
                my $li = length($index);
                if($li > $lw)
                {
                    $words[$i] .= ' ' x ($li-$lw);
                }
                elsif($lw > $li)
                {
                    $index .= ' ' x ($lw-$li);
                }
                push(@indices, $index);
            }
            my $iline = 'Index: '.join(' ', @indices);
            my $wline = 'Words: '.join(' ', @words);
            $iline =~ s/\s+$//;
            $wline =~ s/\s+$//;
            print("$iline\n");
            print("$wline\n");
            # Now print the other sinfo lines that we did not modify.
            foreach my $header ('Word Gloss (en)', 'Word Gloss (es)', 'Morphemes', 'Morpheme Gloss (en)', 'Morpheme Gloss (es)', 'Morpheme Category', 'Sentence', 'Sentence Gloss (en)', 'Sentence Gloss (es)')
            {
                if(defined($sinfo{$header}))
                {
                    print("$header: $sinfo{$header}\n");
                }
            }
            %sinfo = ();
        }
        # Pass all other lines simply through.
        print;
    }
}
