#!/usr/bin/env perl
# Reads UMR file generated by Federica's converter from UD. Identifies variable
# identifiers in sentence graphs and in alignments and modfies them to start
# with a sentence identifier.
# Copyright © 2025 Dan Zeman <zeman@ufal.mff.cuni.cz>
# License: GNU GPL

use utf8;
use open ':utf8';
binmode(STDIN, ':utf8');
binmode(STDOUT, ':utf8');
binmode(STDERR, ':utf8');

my $sid;
while(<>)
{
    if(m/\# :: snt ([0-9]+)/)
    {
        $sid = 's'.$1;
    }
    elsif(defined($sid))
    {
        # Fix variables in sentence graph.
        # Note that sometimes they contain non-English letters although it is unclear whether UMR allows it.
        s:\(([a-záčďéíňóřšťúýž][0-9]*) / :\($sid\1 / :g;
        # Fix variables in alignment.
        s/^([a-záčďéíňóřšťúýž][0-9]*: [0-9]+)-/$sid\1-/g;
    }
    print;
}
